# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ca9bf5cb7797f0aef5cfac2571f6be9bc6608215ece55cd380a71998e5ee1addaab1569a0a507b38c5692e14e5596eade8afb90ff21afa8ef0ce967214902e9

test:
  secret_key_base: 95867e770671816b2c16eec2fcbdae680446e26b35fb3badc3987b5bb9b12254680cb8eda61282270825980b499e7f4f525fd16d033a2d88cf6ea8070ea23eef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
